type ScriptOptions = {
    clientId: string;
} & Partial<Pick<HTMLScriptElement, "defer" | "async" | "integrity">>;

const csURL = "https://t.contentsquare.net/uxa/";

/**
 * Appends the contentsquare script to document.head
 * @param {ScriptOptions} scriptOptions - Options for injecting the script
 * @param {string} scriptOptions.clientId - Client id, provided by Contentsquare.com (e.g.: 'a6f73d509') - Mandatory.
 * @param {boolean} [scriptOptions.defer=false] - Script will be fetched in parallel with the HTML parsing, but execution will occur after the HTML document has been fully parsed.
 * @param {boolean} [scriptOptions.async=true] - Script will be fetched in parallel with the HTML parsing, and it will be executed as soon as it is available, even if the HTML document is not fully parsed.
 * @param {string} [scriptOptions.integrity] - Integrity hash (SRI) of Contentsquare script. Must be generated by Contentsquare.
 * @returns {HTMLScriptElement} The contentsquare script that was appended to document.head
 */

export function injectContentsquareScript(scriptOptions: ScriptOptions): HTMLScriptElement {

    const scriptElement = document.createElement("script");

    scriptElement.type = "text/javascript";

    scriptElement.defer =
        typeof scriptOptions.defer === "boolean" ? scriptOptions.defer : false;

    scriptElement.async =
        typeof scriptOptions.async === "boolean" ? scriptOptions.async : true;

    if (scriptOptions.integrity) {
        scriptElement.integrity = scriptOptions.integrity;
    }

    scriptElement.crossOrigin = "anonymous";

    scriptElement.src = csURL + scriptOptions.clientId + ".js";

    // @ts-ignore
    window._uxa = window._uxa || [];

    return document.head.appendChild(scriptElement);

}
